version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tcc_database_dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SenhaBancaTcc123!
    ports:
      - "1433:1433"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tcc_backend_dev
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=QuizGamificadoDB;User Id=sa;Password=SenhaBancaTcc123!;TrustServerCertificate=True;
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    ports:
      - "5092:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    container_name: tcc_frontend_dev
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host