version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tcc_database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SenhaBancaTcc123!
    ports:
      - "1433:1433"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tcc_backend
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=QuizGamificadoDB;User Id=sa;Password=SenhaBancaTcc123!;TrustServerCertificate=True;
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    ports:
      - "5092:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tcc_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"